-- https://leetcode.com/problems/count-and-say/description/

cns :: Int -> String
cns 1 = "1"
cns n = decode (cns (n - 1))
  where
    -- generated by copilot
    decode :: String -> String
    decode [] = []
    -- count the number of consecutive elements
    -- takeWhile (==x) (x:xs) returns a list of consecutive x's
    -- use dropWhile to remove the consecutive x's (counted by takeWhile)
    decode (x : xs) = (show (length (takeWhile (== x) (x : xs)))) ++ [x] ++ (decode (dropWhile (== x) (x : xs)))


map cns [1..5]